version: '3.8'

services:
  python_app:
    image: python:3.10-slim
    container_name: renting_vs_owning_calc
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python -m src.visual.dashboard"